# Generated by Django 4.0.4 on 2022-04-24 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_bio_user_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverify',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 9, 39, 20, 335496, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='confirmation_code',
            field=models.IntegerField(default='922518'),
        ),
    ]
