# Generated by Django 4.0.4 on 2022-04-24 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userverify_confirmation_code_clientuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuuid',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 12, 57, 30, 577432, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clientuuid',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='confirmation_code',
            field=models.IntegerField(default='630066'),
        ),
    ]
