# Generated by Django 4.0.4 on 2022-04-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_clientuuid_user_alter_clientuuid_expire_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientUUID',
        ),
        migrations.AlterField(
            model_name='userverify',
            name='confirmation_code',
            field=models.IntegerField(default='271574'),
        ),
    ]
