# Generated by Django 4.0.4 on 2022-04-24 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_clientuuid_alter_userverify_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverify',
            name='confirmation_code',
            field=models.IntegerField(default='666013'),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 24, 18, 8, 54, 384418, tzinfo=utc)),
        ),
    ]
