# Generated by Django 4.0.4 on 2022-04-24 19:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_userverify_confirmation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.IntegerField(default='667141')),
                ('expire', models.DateTimeField(default=datetime.datetime(2022, 4, 24, 19, 11, 31, 764611, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserVerify',
        ),
    ]
