# Generated by Django 4.0.4 on 2022-04-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userverify_expire_alter_userverify_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverify',
            name='confirmation_code',
            field=models.IntegerField(default='526419'),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='expire',
            field=models.DateTimeField(default=1650796573.501329),
        ),
    ]
