# Generated by Django 4.0.4 on 2022-04-24 12:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userverify_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverify',
            name='confirmation_code',
            field=models.IntegerField(default='726253'),
        ),
        migrations.CreateModel(
            name='ClientUUID',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('expire', models.DateTimeField(default=datetime.datetime(2022, 7, 23, 12, 56, 47, 196310, tzinfo=utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
