# Generated by Django 4.0.4 on 2022-04-24 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_clientuuid_user_alter_clientuuid_expire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuuid',
            name='user',
        ),
        migrations.AlterField(
            model_name='clientuuid',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 13, 33, 19, 890723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='confirmation_code',
            field=models.IntegerField(default='161072'),
        ),
    ]
